import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./.shared/components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CJ SPRINGS | RESORTES ARGENTINOS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="https://res.cloudinary.com/dabrn7e05/image/upload/v1700014885/assets/CJ-180x180-_3_-min_clkbmp.webp"
      />
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
